Project ExploreWithMe: Main v0.1.0
KosSpb/java-explore-with-me pull request #4
Opened 2023-09-08 04:15 UTC by KosSpb

<feat>: реализовать логику основного сервиса при помощи классов CategoryService, CompilationService, EventService, LocationService, RequestForEventService, UserService;
<feat>: реализовать контроллеры: AdminController для доступа администратора, PrivateController для доступа авторизованных пользователей, PublicController для любых пользователей;
<feat>: реализовать интерфейсы DAO для взаимодействия с базой данных: CategoryRepository, CompilationRepository, EventRepository, LocationRepository, RequestForEventRepository, UserRepository;
<feat>: реализовать модели данных Event, Category, Compilation, Location, RequestForEvent, User, а также DTO-модели этих сущностей для взаимодействия с контроллерами и передачи данных;
<feat>: реализовать интерфейсы мапперов CategoryMapper, CompilationMapper, EventMapper, LocationMapper, RequestForEventMapper, UserMapper;
<feat>: реализовать enum классы EventModerationAction, EventModerationState, EventsSortType, RequestForEventStatus;
<feat>: реализовать обработчик исключения ErrorHandler для основного сервиса, а также модель данных ErrorResponse для взаимодействия с ним;
<feat>: реализовать исключения ConditionsNotMetException, IncorrectRequestException, LimitReachedException, NotFoundException для основного сервиса;
<refactor>: изменить в методе getStats(), в классе StatsClient сервиса статистики, создание строки URI с помощью StringBuilder на String.join();
<fix>: исключить подмодуль client модуля stats из сборки;

2023-09-09 07:43 UTC, alexache requested changes

2023-09-09 07:43 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/controller/PublicController.java
> +                onlyAvailable, eventsSortType, from, size, request);
Можно передавать не объект реквеста целиком, а только 2 нужных свойства

2023-09-09 07:43 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/dto/request/UpdateStatusOfRequestsForEventDto.java
> +    @NotNull(message = "Field: requestIds. Error: must not be null.")
МОжет еще и не пустой список?

2023-09-09 07:43 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/CompilationService.java
> +    @Validated(OnCreate.class)
Зачем валидации в сервисе?

2023-09-09 07:43 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/CompilationService.java
> +                eventsOfCompilation = new HashSet<>();
Если нужны пустые списки/листы: то лучше использовать Collections.emptySet(), emptyLis()t

2023-09-09 07:43 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/model/Event.java
> +    private Integer confirmedRequests;
Это не должно храниться в таблице событий, а получаться запросом к таблице с заявками на участие

2023-09-09 07:43 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/RequestForEventService.java
> +                eventRepository.save(eventToRequestIn);
Это очень плохой способ и с дублированием информации

2023-09-09 07:43 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/UserService.java
> +        this.userMapper = Mappers.getMapper(UserMapper.class);
Почему спринг не справится с созданием объекта маппера?

2023-09-09 07:43 UTC, alexache commented on core/src/main/resources/schema.sql
> +  confirmed_requests INTEGER NOT NULL,
лишнее

2023-09-09 21:36 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/controller/AdminController.java
> +            @RequestParam(value = "from", defaultValue = "0") int from,
Добавил.

2023-09-09 22:06 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/controller/PublicController.java
> +                onlyAvailable, eventsSortType, from, size, request);
Исправил.

2023-09-09 22:15 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/dto/request/UpdateStatusOfRequestsForEventDto.java
> +    @NotNull(message = "Field: requestIds. Error: must not be null.")
Исправил.

2023-09-09 22:37 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/service/CompilationService.java
> +    @Validated(OnCreate.class)
Перенёс в контроллеры.

2023-09-09 22:52 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/service/CompilationService.java
> +                eventsOfCompilation = new HashSet<>();
Поменял. Я правильно понимаю, что это нужно для того, чтобы было очевиднее что в дальнейшем такая коллекция использоваться не будет?

2023-09-09 23:18 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/service/UserService.java
> +        this.userMapper = Mappers.getMapper(UserMapper.class);
Спринг справляется. Я забыл обновить конструктор.

2023-09-10 00:15 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/model/Event.java
> +    private Integer confirmedRequests;
Убрал.

2023-09-10 00:17 UTC, KosSpb commented on core/src/main/resources/schema.sql
> +  confirmed_requests INTEGER NOT NULL,
Удалил.

2023-09-10 09:51 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/service/RequestForEventService.java
> +                eventRepository.save(eventToRequestIn);
Постарался исправить.

2023-09-10 10:01 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/dto/request/UpdateStatusOfRequestsForEventDto.java
> +    @NotNull(message = "Field: requestIds. Error: must not be null.")
А можешь, пожалуйста, подсказать? Можно ли наследовать одно DTO от другого? Не в смысле самой возможности, а  принято ли так, или наоборот нежелательно?

2023-09-11 19:26 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/dto/request/UpdateStatusOfRequestsForEventDto.java
> +    @NotNull(message = "Field: requestIds. Error: must not be null.")
Очень сильно зависит. Относится ли к одной и той же сущности, есть ли кейсы для полиморфизма. В обычных ситуациях лучше делать проще, разные ДТО не связанные наследованием. С другой стороны много ДТО, которые про одну сущность, но отличаются 1-2 полями может и не стоит Очень субъективная тема. Можно конкретно посмотреть на какой-нибудь пример, где сомневаешься?

2023-09-11 19:28 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/CompilationService.java
> +                eventsOfCompilation = new HashSet<>();
Как один из вариантов, да. Но важнее с точки зрения Garbage Collector - Java приложение работает лучше, если не генерится много "мусорных" короткоживущих объектов. Меньше работы коллектору - меньше задержки и вычислений

2023-09-11 19:35 UTC, alexache approved these changes

2023-09-11 19:35 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/dao/EventRepository.java
> +            "(SELECT COUNT(r.id) " +
Очень суровые запросы! (это не запрос на исправление)

2023-09-11 19:35 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/CompilationService.java
> +            eventDtosOfCompilation = eventsOfCompilation.stream()
Это не самый оптимальный способ, это квадратичный алгоритм. Лучше переложить результат подсчета количества заявок в мапу, где ключ - айди события: а значение количество заявок. Тогда это будет линейный алгоритм

2023-09-11 19:40 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/dto/request/UpdateStatusOfRequestsForEventDto.java
> +    @NotNull(message = "Field: requestIds. Error: must not be null.")
Ну вот у меня есть EventResponseDto и EventFullInfoResponseDto. И второй фактически просто дополняет первый полями. И если EventFullInfoResponseDto можно было бы отнаследовать от EventResponseDto, то метод setViewsAndConfirmedRequests() в EventService можно было бы сделать с дженериками - private <T extends EventResponseDto> void setViewsAndConfirmedRequests(List<EventViews> eventsViews, List<ConfirmedRequestsQuantity> confirmedRequestsQuantityByEvents, T eventResponseDto), чтобы и в методах с EventFullInfoResponseDto применять, а не только с методами где EventResponseDto используется. Я не проверял такую реализация, правда. Но наверное должна же работать? Вот такой пример.

2023-09-11 19:42 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/dto/request/UpdateStatusOfRequestsForEventDto.java
> +    @NotNull(message = "Field: requestIds. Error: must not be null.")
Куда-то удалились дженерики в методе. 
private "<T extends EventResponseDto>" void setViewsAndConfirmedRequests(List<EventViews> eventsViews,
                                              List<ConfirmedRequestsQuantity> confirmedRequestsQuantityByEvents,
                                              T eventResponseDto)

2023-09-11 20:06 UTC, merged

2023-09-13 04:01 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/service/CompilationService.java
> +            eventDtosOfCompilation = eventsOfCompilation.stream()
Спасибо за полезный совет. Надеюсь я правильно исправил.