Feature comments
KosSpb/java-explore-with-me pull request #5
Opened 2023-09-13 05:53 UTC by KosSpb

2023-09-14 05:15 UTC, alexache requested changes

2023-09-14 05:15 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/controller/AdminController.java
> +    @DeleteMapping("/comments/{commentId}")
Хорошо бы еще дать админам возможность редактировать пользовательские комментарии, "модерировать"

2023-09-14 05:15 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/model/Comment.java
> +    private LocalDateTime created;
Можно еще добавить время редактирования комментария

2023-09-14 05:15 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/CommentService.java
> +
(опционально) можно еще добавить проверку, что юзер посещал событие (через таблица подтвержденных заявок)

2023-09-14 13:24 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/controller/AdminController.java
> +    @DeleteMapping("/comments/{commentId}")
Добавил.

2023-09-15 10:52 UTC, alexache approved these changes

2023-09-15 10:52 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/CommentService.java
> +        commentToUpdate.setEditedAt(LocalDateTime.now());
Время апдейта тоже можно прстоавлять автоматически, это относится к аудит полям и при включенном айдите довольно легко делается еще и версионирование (при необходимости)

2023-09-15 10:52 UTC, alexache commented on core/src/main/java/ru/practicum/explorewithme/service/CommentService.java
> +        if (!commentToUpdate.getIsEdited()) {
МОжно просто всегда безусловно ставить в true, никто не пострадает от этого

2023-09-15 15:50 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/service/CommentService.java
> +        commentToUpdate.setEditedAt(LocalDateTime.now());
То есть можно не устанавливать значение полю editedAt, а просто как-то в БД отслеживать перевод isEdited в true, а уже БД сама timestamp поставит? Правильно понимаю или как-то иначе это реализовать нужно?

2023-09-15 15:51 UTC, KosSpb commented on core/src/main/java/ru/practicum/explorewithme/service/CommentService.java
> +        if (!commentToUpdate.getIsEdited()) {
Исправил.

Александр, спасибо огромное за добрые слова и твои ценные комментарии, сопровождавшие все ревью моих работ на протяжении этого курса.  Я очень тебе благодарен, и рад что у меня был такой отличный ревьюер все эти долгие 11 месяцев. Буду стараться и дальше держать тот уровень качества кода, к которому ты меня приучил, и продолжу развивать свои навыки.
С благодарностью, Константин.

2023-09-15 15:52 UTC, merged